### ISSUE TITLE
Different API endpoints

### ISSUE THREAD

**Issue by aksareen** [hasgeek/internship-test-python-flask#1]
The API endpoints for increment and decrement inputs are different. Shouldn't they be same since we're creating a common endpoint for both ?

https://github.com/hasgeek/internship-test-python-flask/blob/master/templates/index.html#L18
https://github.com/hasgeek/internship-test-python-flask/blob/master/templates/index.html#L24

**Comment by karthikb351** [comment]
Oh shoot! Yeah, that's a typo - pushed a fix for that dcbf9a15a297a7af256b400048e8757b4f8f46c3
